### ISSUE TITLE
Empty environment variables make the replicator exit with code 0

### ISSUE THREAD

**Issue by kjkoster** [foundation-zero/influx-replicator#2]
When I set a bad value in a `docker-compose` and that resolves to an empty string, the replicator starts and quietly exits with code 0. Expected behaviour is for the replicator to treat empty strings as non-existent and exit with a message and code != 0.

Example to reproduce, assuming `XXX` is not set:
```
  influx-replicator:
    image: ghcr.io/foundation-zero/influx-replicator:main
    depends_on:
      - influxdb
    environment:
      INFLUXDB_SOURCE_URL: ${INFLUXDB_SOURCE_URL}
      INFLUXDB_SOURCE_ORGANISATION: ${INFLUXDB_SOURCE_ORGANISATION}
      INFLUXDB_SOURCE_TOKEN: ${INFLUXDB_SOURCE_TOKEN}
      INFLUXDB_SOURCE_BUCKET: ${INFLUXDB_SOURCE_BUCKET}
      INFLUXDB_SINK_URL: ${INFLUXDB_SINK_URL}
      INFLUXDB_SINK_ORGANISATION: ${INFLUXDB_SINK_ORGANISATION}
      INFLUXDB_SINK_TOKEN: ${INFLUXDB_SINK_TOKEN}
      INFLUXDB_SINK_BUCKET: ${XXX}
```
